language: python
python: 3.9
env:
  global:
  - LOCAL_REPO: multi2vec-clip
  - REMOTE_REPO: semitechnologies/multi2vec-clip
  - secure: edOP2kFjnOBqXMKVyvkPnUtcupzX5msoyUymMYlkHdfMfCiVGZ9bDzxMW4DMN1ib2qYrXtZwiZKwb7eb0oiRETYvCnvzJV/F3FOqzatlEvXX8hpjiZ/gMoQeF+usiYG9VsAxdlD+RxFGj1cBuQmoPo92bA1NP+LBrbgJJxYK0yPdP4kiccHU52DuLOp8HP4kDwdpEQCNi0NX9cDQSSCGZcF6fUwdY9Cf8UnhUZ1rW+A0mDLElJ5ExFUDmDv6JFNTYB7UsOaAX4ykPPjI7F+0sTKtAWVitUR0i/sfoPDqq6oPWb/pKzKjvh/K9JBQ7skLlRbMQi2StByUAwb5bygi1ycMbvq3JiVJVLzhycC2s9CVn0n/SeP/31ih2ERx0i4nUvAVO2dzR9M/faCbW/xcQz8x68qNoHo6vGC2cboU3CwlxcAYfhJnqszQyD37FZi/vgwe6s07oNp7citx1zDPI3AeW3u9o8cvNgtlOr4frIDBmqovzdHIKdOTXQKBew9sFeFZZdDWwyBIsFPyWfcVY+bJCZ1Q5qHkNlXFQODhqtpze96loBlrcjRPWIf787fK5jIDAcnvgjokJcyuj38MziM3vRqTBenJEIl9db9CEwpD7A1YGg0xcwhw+WGhRT4uY48dJE3rrYp7g+mWEWr+tMLEi/FXugDwikG/ozPXZ10=
  - secure: 4h3NAbGWJ2x7rFuUuQZNEgOm0waIh2aEQQAbHL04KUzDCCc35DcIybFgoz33Ahv2W75JzL2HgXanU3uVbu7f9ySvyos4p4+SD3ENl5V9o1r7N6/w+dBzkhy5CS1bjs6nERn4ORDGNNDfjT+VxWFkvvmLHjU7L3CgWDPDkOWAR7uWgECRO9U1+/+Y1cdU/r2bKWqIXmsVWuraPe8fMOJeBy36bd2CZytKaLcSJVN92oy6eEEUZIx67Exb5x5wKgm51bJ7om0ukfyuGvb6Bbev381QkY6mUKbzToDvOGejSo6+NpzTyhpTxEiMTpa8akwwMcYbhl396vV69aDAxFaMd5ou4D3+uzal22JvXA76VGTYtdUhwCxIahIZ2/SZ3Ifs+mzAW/zVwT7ow8f9GTU2FNdqsVQEKorm2HnVBikFQYWsP2OA+c2mCJVilAXMo/2QKjzUHc4StvMg/y11JQlRGIY8DscxiOsSg/HptrOvBpxWv277tOhGjQ1UhaZOYhbdyyLIP042/5orTbhm6Tq1GRy36dzeRkS/DzGtnqP8Xu60sgYj8nvBhb+ySLJVkwUtxgIZx29jg7rRNZPogGgC/82EqCk03MqaQz7d8e3pH6zRIxU9WOD3sH9rjSKJhJhyWrJfTEoUtDz488o8GIL6xHfvjS/BI8/J0M1s1getK80=
install: echo skipping default travis install script
jobs:
  include:
    # always run test, etc. for this model
    - env:
        CLIP_MODEL_NAME: clip-ViT-B-32
        TEXT_MODEL_NAME: clip-ViT-B-32
        MODEL_TAG_NAME: sentence-transformers-clip-ViT-B-32
      stage: buildanddeploy
    - env:
        CLIP_MODEL_NAME: clip-ViT-B-32
        TEXT_MODEL_NAME: sentence-transformers/clip-ViT-B-32-multilingual-v1
        MODEL_TAG_NAME: sentence-transformers-clip-ViT-B-32-multilingual-v1
      stage: buildanddeploy
    - env:
        CLIP_MODEL_NAME: openai/clip-vit-base-patch16
        TEXT_MODEL_NAME: openai/clip-vit-base-patch16
        MODEL_TAG_NAME: openai-clip-vit-base-patch16
      stage: buildanddeploy

    - name: Build the base for custom images
      script: GIT_BRANCH=$TRAVIS_BRANCH GIT_TAG=$TRAVIS_TAG GIT_PULL_REQUEST=$TRAVIS_PULL_REQUEST cicd/build_custom_base.sh
      stage: postbuild
script:
- cicd/build.sh || travis_terminate 1
- cicd/test.sh || travis_terminate 1
- |-
  # Push docker image
  GIT_BRANCH=$TRAVIS_BRANCH \
  GIT_TAG=$TRAVIS_TAG \
  GIT_PULL_REQUEST=$TRAVIS_PULL_REQUEST \
  travis_wait 120 cicd/docker_push.sh || travis_terminate 1
before_install: 
  # install a newer docker version which supports buildx
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
before_script:
  # login to docker at the very beginning, so we don't run into rate-limiting
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# currently the latest available - so we can install the latest docker
dist: bionic